### ISSUE TITLE
inappbrowser crashing on release mode

### ISSUE THREAD

**Issue by umair-dpl** [proyecto26/react-native-inappbrowser#174]
inappbrowser is crashing on release modern android, I am not sure about the cause but I have found it crashing, anyone can let me know the cause ? 
//passing the url from another function 
   this.openLink(Url);

openLink= async(url) => {
  try {
    await InAppBrowser.isAvailable()
    InAppBrowser.open(url, { 
      // Android Properties
      showTitle: true,
      toolbarColor: 'black',
      secondaryToolbarColor: 'black',
      enableUrlBarHiding: true,
      enableDefaultShare: true,
      forceCloseOnRedirection: false,
    }).then((result) => {
    //  Alert.alert(JSON.stringify(result))
    })
  } catch (error) {
  //  Alert.alert(error.message)
  }
}
what is causing the crash which is working on debug mode but not on release mode, kindly let me know ASAP

**Comment by jdnichollsc** [comment]
Please share logs of the error in order to reopen this issue. We're using this plugin in multiple apps and they're working as expected in release mode :)

**Comment by umair-dpl** [comment]
org.greenrobot.eventbus.EventBusException: Subscriber class com.proyecto26.inappbrowser.RNInAppBrowser and its super classes have no public methods with the @Subscribe annotation
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
        at com.proyecto26.inappbrowser.RNInAppBrowser.registerEventBus(RNInAppBrowser.java:212)
        at com.proyecto26.inappbrowser.RNInAppBrowser.open(RNInAppBrowser.java:137)
        at com.proyecto26.inappbrowser.RNInAppBrowserModule.open(RNInAppBrowserModule.java:33)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:207)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:818)

**Comment by jdnichollsc** [comment]
Check the last step here https://github.com/proyecto26/react-native-inappbrowser#android

**Comment by anshucodebook15** [comment]
> inappbrowser is crashing on release modern android, I am not sure about the cause but I have found it crashing, anyone can let me know the cause ? //passing the url from another function this.openLink(Url);
> 
> openLink= async(url) => { try { await InAppBrowser.isAvailable() InAppBrowser.open(url, { // Android Properties showTitle: true, toolbarColor: 'black', secondaryToolbarColor: 'black', enableUrlBarHiding: true, enableDefaultShare: true, forceCloseOnRedirection: false, }).then((result) => { // Alert.alert(JSON.stringify(result)) }) } catch (error) { // Alert.alert(error.message) } } what is causing the crash which is working on debug mode but not on release mode, kindly let me know ASAP

sir have you find the answer, because mine app is also crashed in release mode

**Comment by jdnichollsc** [comment]
> > inappbrowser is crashing on release modern android, I am not sure about the cause but I have found it crashing, anyone can let me know the cause ? //passing the url from another function this.openLink(Url);
> > openLink= async(url) => { try { await InAppBrowser.isAvailable() InAppBrowser.open(url, { // Android Properties showTitle: true, toolbarColor: 'black', secondaryToolbarColor: 'black', enableUrlBarHiding: true, enableDefaultShare: true, forceCloseOnRedirection: false, }).then((result) => { // Alert.alert(JSON.stringify(result)) }) } catch (error) { // Alert.alert(error.message) } } what is causing the crash which is working on debug mode but not on release mode, kindly let me know ASAP
> 
> sir have you find the answer, because mine app is also crashed in release mode

Please check native issues with Android Logcat and let us know the logs! 👍

**Comment by rutul-mehta** [comment]
@umair-dpl  Did you find any answer because my app is also crashing
