### ISSUE TITLE
App crashing while opening any URL

### ISSUE THREAD

**Issue by jdarosaj** [proyecto26/react-native-inappbrowser#268]
### Which platform(s) does your issue occur on?
I tested it on Android emulator.

### Please, provide the following version numbers that your issue occurs with:
"react-native": "0.63.4",
"react-native-inappbrowser-reborn": "^3.5.1",

### Please, tell us how to recreate the issue in as much detail as possible. 
When opening any URL without protocol the app crashes.
E.g.: Using 'www.google.com' instead of 'http://www.google.com' makes the app crash.

Currently I'm having to manually check if the link has the protocol in it. But manually checking this, is probably not a good solution.

### Is there any code involved? 
```
    const isAvailable = await InAppBrowser.isAvailable();
    if (isAvailable) {
      await InAppBrowser.open(url, {
        // iOS Properties
        dismissButtonStyle: 'cancel',
        preferredBarTintColor: Colors.yellowTheme,
        preferredControlTintColor: 'white',
        readerMode: false,
        animated: true,
        modalPresentationStyle: 'pageSheet',
        modalTransitionStyle: 'coverVertical',
        modalEnabled: true,
        enableBarCollapsing: true,
        // Android Properties
        showTitle: false,
        toolbarColor: Colors.yellowTheme,
        secondaryToolbarColor: Colors.yellowTheme,
        enableUrlBarHiding: true,
        enableDefaultShare: false,
        forceCloseOnRedirection: false,
      });
    } else {
      await Linking.openURL(url);
    }
```

This is the log from `adb logcat`:

```
05-24 14:25:02.275 19476 19476 D AndroidRuntime: Shutting down VM
05-24 14:25:02.276 19476 19476 E AndroidRuntime: FATAL EXCEPTION: main
05-24 14:25:02.276 19476 19476 E AndroidRuntime: Process: -------, PID: 19476
05-24 14:25:02.276 19476 19476 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{app-id/com.proyecto26.inappbrowser.ChromeTabsManagerActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=www.google.com flg=0x44800000 pkg=com.android.chrome (has extras) }
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=www.google.com flg=0x44800000 pkg=com.android.chrome (has extras) }
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2051)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1709)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5192)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5150)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5521)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5489)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at com.proyecto26.inappbrowser.ChromeTabsManagerActivity.onCreate(ChromeTabsManagerActivity.java:52)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7802)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7791)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
05-24 14:25:02.276 19476 19476 E AndroidRuntime: 	... 11 more

```

**Comment by achigo16** [comment]
i think you must update your ProGuard config

**Comment by jdnichollsc** [comment]
Thanks for reporting this issue, please check your ProGuard config 👍

**Comment by abhisekpadhi** [comment]
> Thanks for reporting this issue, please check your ProGuard config 👍

Can confirm simply updating proguard config works with RN 0.62.0.

Appending these lines to progurad config fixed crash in release build.

```
-keepattributes *Annotation*
-keepclassmembers class ** {
  @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
```
