### ISSUE TITLE
React native 0.67.5 crash

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [proyecto26/react-native-inappbrowser#457]
### Make sure to check the demo app(s) for sample usage 

I am using react native 0.67.5. Debug build is working fine. But for android release build, on opening the in app broswer my app crashes. The adb logcat shows this:
Subscriber class com.proyecto26.inappbrowser.c and its super classes have no public methods with the @Subscribe annotation
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at s.b.a.p.a(SubscriberMethodFinder.java:7)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at s.b.a.c.p(EventBus.java:2)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.proyecto26.inappbrowser.c.l(RNInAppBrowser.java:2)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.proyecto26.inappbrowser.c.k(RNInAppBrowser.java:59)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.proyecto26.inappbrowser.RNInAppBrowserModule.open(RNInAppBrowserModule.java:2)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at java.lang.reflect.Method.invoke(Native Method)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at android.os.Handler.handleCallback(Handler.java:938)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at android.os.Looper.loopOnce(Looper.java:201)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at android.os.Looper.loop(Looper.java:288)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
06-07 11:42:39.197 14321 14454 E IBG-CR  : 	at java.lang.Thread.run(Thread.java:920)

Any reason why the crash is happening? Please do help

### Which platform(s) does your issue occur on?
- Android
- Android 12
- emulator

### Please, provide the following version numbers that your issue occurs with:
react native 0.67.5

### Please, tell us how to recreate the issue in as much detail as possible. 

Used the sample code provided in the documentation

**Comment by angelavanessaa** [comment]
This worked for me:
https://github.com/proyecto26/react-native-inappbrowser/issues/15#issuecomment-439477853
